name: crypto_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animated_search_bar: ^2.5.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  intl: ^0.18.1
  syncfusion_flutter_charts: ^22.1.38

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
